version: '3'
services:
   satoblock:
     build: .
     image: satoblock:rdbc-v3
     entrypoint: ./satoblock
     volumes:
       - /data/bitcoin-sv-blocks/blocks:/data/bitcoin-sv-blocks/blocks:ro
       - ./conf:/data/conf:ro
       - ./cmd:/data/cmd
     labels:
       - "name=satoblock"
     logging:
       driver: "json-file"
       options:
         labels: "name"
         max-size: "1g"
         max-file: "3"
